# sudo apt install -y keychain
# 2001  cd ~/.ssh
# 2002  ls -l
# 2003  eval `keychain --eval --agents ssh pegasus`
# 2004  source ~/.bashrc
# GREYNOISE_API_KEY=ds1o2TjEBkjFIGPG7qOPZgKk7kGNQHTrMUl0sJgaWrbrlCKc5RYGISYSed65nPo7 && curl -H "key: ${GREYNOISE_API_KEY}" -L https://api.greynoise.io/v1/workspaces/dcbac25e-f1af-4d2d-8718-933ba025f20f/sensors/bootstrap/script
#| sudo bash -s -- -k ${GREYNOISE_API_KEY}
---
 - hosts: uppity
   become: true
   tasks:
    - name: Make sure I hae root access by getting hash of shadow file
      command: "md5sum /etc/shadow"
    - name: Download the bootstrap.sh script and copy to /tmp
      ansible.builtin.get_url:
        url: https://api.greynoise.io/v1/workspaces/dcbac25e-f1af-4d2d-8718-933ba025f20f/sensors/bootstrap/script
        dest: /tmp/bootstrap.sh
        headers:
          key: ds1o2TjEBkjFIGPG7qOPZgKk7kGNQHTrMUl0sJgaWrbrlCKc5RYGISYSed65nPo7
    - name: Execute /tmp/bootstrap.sh
      command: "bash /tmp/bootstrap.sh -s 22 -k ds1o2TjEBkjFIGPG7qOPZgKk7kGNQHTrMUl0sJgaWrbrlCKc5RYGISYSed65nPo7"
