---
- hosts: redhat
  become: true
  tasks:
    - name: install web components
      yum: name=httpd state=present update_cache=yes

    - name: ensure apache2 started
      service: name=httpd state=started enabled=yes
  
