---
- name: fetch module demo
  hosts: upsilon
  become: true
  vars:
    log_file: "/home/svcMaestro/IOT/devices_local.log"
    dump_dir: "/home/svcMaestro/devices.log"
  tasks:
    - name: fetch log
      ansible.builtin.fetch:
        src: "{{ log_file }}"
        dest: "{{ dump_dir }}"
 
