---
- name: fetch module demo
  hosts: upsilon
  become: true
  vars:
    log_file: "/var/log/network_test_results.csv"
    dump_dir: "/srv/Splunk/Speed"
  tasks:
    - name: fetch log
      ansible.builtin.fetch:
        src: "{{ log_file }}"
        dest: "{{ dump_dir }}"
 
