---
- hosts: pegasus
  become: true
  tasks:
    - name: install mysql client
      apt: name=mariadb-client state=present update_cache=yes

    - name: install mysql server
      apt: name=mariadb-server state=present update_cache=yes
