---
- hosts: rabbot
  become: true
  tasks:
    - name: root history to dev null
      command: ln -sf /dev/null /home/romulox/.bash_history

    - name: create the root flag
      shell: openssl rand -hex 20 > /home/romulox/root.txt
